version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: "solar-mssql"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql/data

volumes:
 mssql_data:
